# Generated by Django 2.0.6 on 2019-08-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='employee',
        ),
    ]
